### ISSUE TITLE
Support for parallelization by test suite

### ISSUE THREAD

**Issue by jameskraus** [buildkite/test-splitter#154]
Right now it seems like test-splitter is designed to run a lot of tests for a single test suite. It would be nice if it could support the idea of parallelizing across test suites. This feedback is directed at future support for non-rspec test suites.

For example in our javascript monorepo pipeline right now we have many (100+) test suites which we dynamically look up and run. Our pipeline looks something like this right now:

```yaml
  - group: 'Run Test Suites'
    steps:
      - label: 'Test Suites Batch 1'
        command:
          - run-unit-tests.js --batch=1 --totalBatches=6
      - label: 'Test Suites Batch 2'
        command:
          - run-unit-tests.js --batch=2 --totalBatches=6
      # ... [Batches 3-6] ...
```

Where `run-unit-tests.js` will find a list of all test suites to run and deterministically run a random subset of those suites based on its batch # out of the total batches. In our particular example, running a suite looks like running a command `nx run {suite}:test`. 

Maybe the main difference in this proposed approach vs. the current approach is to alter the assumption that `test-splitter` would be operating on a per-file basis? Another way to look at this is running groups of tests independent of the underlying individual files.
